import type { FeedPost } from '@/types/feed';

/**
 * Sample community posts. Places appear on the map because people post about them.
 */
export const feedPosts: FeedPost[] = [
  {
    id: 'post-001',
    userName: 'Maya',
    userHandle: 'maya_rva',
    avatarColor: '#C44B2F',
    activity: 'recommends',
    caption: 'Octopus stole the show. Bring friends and get the shared plates — Oregon Hill night done right.',
    placeId: 'plc-lopossum',
    placeName: "L'Opossum",
    placeCategory: 'eat',
    placeSubcategory: 'French · fine dining',
    placeEmoji: '🍽️',
    placePriceLevel: '$$$$',
    placeLat: 37.5401,
    placeLng: -77.4532,
    neighborhood: 'Oregon Hill',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    likes: 42,
    comments: 8,
    shares: 3,
    imageColor: '#2A1F1A',
    imageEmoji: '🍽️',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-002',
    userName: 'Jordan',
    userHandle: 'jordgoesout',
    avatarColor: '#6B4F7A',
    activity: 'at-event',
    caption: 'Line was worth it. Catch this before it sells out — Brown’s Island at golden hour.',
    eventTitle: "Sunset on Brown's Island",
    neighborhood: 'Downtown',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    likes: 88,
    comments: 14,
    shares: 11,
    imageColor: '#1A2433',
    imageEmoji: '🌅',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-003',
    userName: 'Sam',
    userHandle: 'saminthefan',
    avatarColor: '#2F6B52',
    activity: 'checked-in',
    caption: 'Morning coffee run. Quiet corner table if you get here early.',
    placeId: 'plc-blanchards',
    placeName: "Blanchard's Coffee",
    placeCategory: 'cafes',
    placeSubcategory: 'Coffee · study spot',
    placeEmoji: '☕',
    placePriceLevel: '$',
    placeLat: 37.5521,
    placeLng: -77.4624,
    neighborhood: 'The Fan',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    likes: 19,
    comments: 2,
    shares: 1,
    imageColor: '#3D2B1F',
    imageEmoji: '☕',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-004',
    userName: 'Alex',
    userHandle: 'alexscotts',
    avatarColor: '#D4922A',
    activity: 'visited',
    caption: "Scott's Addition night. Cocktails first, then whatever's playing nearby.",
    placeId: 'plc-jasper',
    placeName: 'The Jasper',
    placeCategory: 'bars',
    placeSubcategory: 'Cocktails · late night',
    placeEmoji: '🍸',
    placePriceLevel: '$$',
    placeLat: 37.5694,
    placeLng: -77.4688,
    neighborhood: "Scott's Addition",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    likes: 61,
    comments: 9,
    shares: 4,
    imageColor: '#1F1830',
    imageEmoji: '🍸',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-005',
    userName: 'Riley',
    userHandle: 'rileycarytown',
    avatarColor: '#3D6F8C',
    activity: 'recommends',
    caption: 'Found the perfect jacket and stayed for an hour in the stacks.',
    placeId: 'plc-bygones',
    placeName: 'Bygones Vintage',
    placeCategory: 'shops',
    placeSubcategory: 'Vintage · clothing',
    placeEmoji: '👗',
    placePriceLevel: '$$',
    placeLat: 37.5534,
    placeLng: -77.4801,
    neighborhood: 'Carytown',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    likes: 27,
    comments: 5,
    shares: 2,
    imageColor: '#2C2430',
    imageEmoji: '👗',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-006',
    userName: 'Chris',
    userHandle: 'chrislocal',
    avatarColor: '#4F7A58',
    activity: 'at-event',
    caption: 'Hidden gem energy. Small room, loud band, perfect Friday.',
    eventTitle: 'Live set in the Fan',
    neighborhood: 'The Fan',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 54).toISOString(),
    likes: 73,
    comments: 12,
    shares: 7,
    imageColor: '#1A1A22',
    imageEmoji: '🎸',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-007',
    userName: 'Taylor',
    userHandle: 'tayloreats',
    avatarColor: '#9E3A24',
    activity: 'visited',
    caption: 'Deli classic. Get the pastrami and sit by the window.',
    placeId: 'plc-perlys',
    placeName: "Perly's",
    placeCategory: 'eat',
    placeSubcategory: 'Jewish deli · brunch',
    placeEmoji: '🥯',
    placePriceLevel: '$$',
    placeLat: 37.5412,
    placeLng: -77.4378,
    neighborhood: 'Downtown',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    likes: 34,
    comments: 4,
    shares: 2,
    imageColor: '#2B2118',
    imageEmoji: '🥯',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-008',
    userName: 'Casey',
    userHandle: 'caseybooks',
    avatarColor: '#457B9D',
    activity: 'recommends',
    caption: 'Lost an hour in here again. Best rainy-day shop in Carytown.',
    placeId: 'plc-chopsuey',
    placeName: 'Chop Suey Books',
    placeCategory: 'shops',
    placeSubcategory: 'Bookstore',
    placeEmoji: '📚',
    placePriceLevel: '$$',
    placeLat: 37.5528,
    placeLng: -77.4792,
    neighborhood: 'Carytown',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    likes: 22,
    comments: 3,
    shares: 1,
    imageColor: '#1E2430',
    imageEmoji: '📚',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-009',
    userName: 'Morgan',
    userHandle: 'morgansbread',
    avatarColor: '#2F6B52',
    activity: 'checked-in',
    caption: 'Wood-fired loaf still warm. Church Hill morning sorted.',
    placeId: 'plc-subrosa',
    placeName: 'Sub Rosa Bakery',
    placeCategory: 'cafes',
    placeSubcategory: 'Bakery · coffee',
    placeEmoji: '☕',
    placePriceLevel: '$',
    placeLat: 37.5328,
    placeLng: -77.4165,
    neighborhood: 'Church Hill',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    likes: 51,
    comments: 6,
    shares: 3,
    imageColor: '#3A2A20',
    imageEmoji: '🥖',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80',
  },
  {
    id: 'post-010',
    userName: 'Drew',
    userHandle: 'drewonbroad',
    avatarColor: '#6B4F7A',
    activity: 'at-event',
    caption: 'Show night. Get here early if you want a decent spot.',
    placeId: 'plc-broadberry',
    placeName: 'The Broadberry',
    placeCategory: 'nightlife',
    placeSubcategory: 'Live music · venue',
    placeEmoji: '🪩',
    placePriceLevel: '$$',
    placeLat: 37.5688,
    placeLng: -77.4701,
    neighborhood: "Scott's Addition",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    likes: 67,
    comments: 10,
    shares: 8,
    imageColor: '#1A1528',
    imageEmoji: '🪩',
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=900&q=80',
  },
];
