# Linked project: edorsmasowlidwftzqnh
project_id = "edorsmasowlidwftzqnh"

[auth]
site_url = "citipilot://auth-callback"
additional_redirect_urls = [
  "citipilot://auth-callback",
  "citipilot://auth",
  "exp://**",
  "exp://**/--/auth-callback",
  "exp://**/--/auth",
]
