import type { Place } from '@/types/place';

export const places: Place[] = [
  {
    id: 'plc-001',
    name: "L'Opossum",
    category: 'eat',
    subcategory: 'French · fine dining',
    neighborhood: 'Oregon Hill',
    description: 'Inventive French plates and a cult following.',
    emoji: '🍽️',
    priceLevel: '$$$$',
    lat: 37.5401,
    lng: -77.4532,
    featured: true,
  },
  {
    id: 'plc-002',
    name: 'Perly’s',
    category: 'eat',
    subcategory: 'Jewish deli · brunch',
    neighborhood: 'Downtown',
    description: 'Classic deli energy in the heart of downtown.',
    emoji: '🥯',
    priceLevel: '$$',
    lat: 37.5412,
    lng: -77.4378,
  },
  {
    id: 'plc-003',
    name: 'Sub Rosa Bakery',
    category: 'cafes',
    subcategory: 'Bakery · coffee',
    neighborhood: 'Church Hill',
    description: 'Wood-fired bread and neighborhood coffee.',
    emoji: '☕',
    priceLevel: '$',
    lat: 37.5328,
    lng: -77.4165,
    featured: true,
  },
  {
    id: 'plc-004',
    name: 'Blanchard’s Coffee',
    category: 'cafes',
    subcategory: 'Coffee · study spot',
    neighborhood: 'The Fan',
    description: 'Local roaster with a steady Fan crowd.',
    emoji: '☕',
    priceLevel: '$',
    lat: 37.5521,
    lng: -77.4624,
  },
  {
    id: 'plc-005',
    name: 'The Jasper',
    category: 'bars',
    subcategory: 'Cocktails · late night',
    neighborhood: "Scott's Addition",
    description: 'Craft cocktails in Scott’s Addition.',
    emoji: '🍸',
    priceLevel: '$$',
    lat: 37.5694,
    lng: -77.4688,
    featured: true,
  },
  {
    id: 'plc-006',
    name: 'Triple Crossing Brewing',
    category: 'bars',
    subcategory: 'Brewery · patio',
    neighborhood: 'Fulton',
    description: 'Beer, patio, and a local staple.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5256,
    lng: -77.4122,
  },
  {
    id: 'plc-007',
    name: 'Bygones Vintage',
    category: 'shops',
    subcategory: 'Vintage · clothing',
    neighborhood: 'Carytown',
    description: 'Carytown vintage for a weekend wander.',
    emoji: '👗',
    priceLevel: '$$',
    lat: 37.5534,
    lng: -77.4801,
  },
  {
    id: 'plc-008',
    name: 'Chop Suey Books',
    category: 'shops',
    subcategory: 'Bookstore',
    neighborhood: 'Carytown',
    description: 'Independent bookstore with serious stacks.',
    emoji: '📚',
    priceLevel: '$$',
    lat: 37.5528,
    lng: -77.4792,
    featured: true,
  },
  {
    id: 'plc-009',
    name: 'The Broadberry',
    category: 'nightlife',
    subcategory: 'Live music · venue',
    neighborhood: 'Scott\'s Addition',
    description: 'Live shows and late nights.',
    emoji: '🪩',
    priceLevel: '$$',
    lat: 37.5688,
    lng: -77.4701,
  },
  {
    id: 'plc-010',
    name: 'Carytown Farmers Market',
    category: 'markets',
    subcategory: 'Weekend market',
    neighborhood: 'Carytown',
    description: 'Local produce and makers on market days.',
    emoji: '🥬',
    priceLevel: '$',
    lat: 37.5539,
    lng: -77.4815,
  },
  {
    id: 'plc-011',
    name: 'Legend Brewing Co.',
    category: 'bars',
    subcategory: 'Brewery · river views',
    neighborhood: 'Manchester',
    description: 'Manchester patio with skyline views.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5234,
    lng: -77.4412,
  },
  {
    id: 'plc-012',
    name: 'Croaker’s Spot',
    category: 'eat',
    subcategory: 'Seafood · soul food',
    neighborhood: 'Jackson Ward',
    description: 'Seafood and soul food institution.',
    emoji: '🐟',
    priceLevel: '$$',
    lat: 37.5489,
    lng: -77.4398,
  },
];
