import type { CuratedList, RvaEvent } from '@/types/event';

export const neighborhoods = [
  'Downtown',
  'The Fan',
  "Scott's Addition",
  'Church Hill',
  'Manchester',
  'Carytown',
];

export const vibes = [
  'Food & Drink',
  'Live Music',
  'Family',
  'Nightlife',
  'Networking',
  'Markets',
  'Fitness',
  'Free',
];

export const timeWindows = [
  { id: 'today' as const, label: 'Today' },
  { id: 'weekend' as const, label: 'This Weekend' },
  { id: 'week' as const, label: 'This Week' },
];

export const promotionTiers = [
  { id: 'free' as const, label: 'Free listing', price: 'Free', description: 'Standard neighborhood placement' },
  { id: 'featured' as const, label: 'Featured placement', price: '$25', description: 'Top of feed + map highlight for one event' },
  { id: 'subscription' as const, label: 'Business subscription', price: '$50/mo', description: 'Monthly priority placement + analytics (coming)' },
];

export const events: RvaEvent[] = [
  {
    id: 'rva-001',
    title: "Sunset on Brown's Island",
    neighborhood: 'Downtown',
    vibe: ['Live Music', 'Free'],
    day: 'Friday',
    time: '7:00 PM',
    venue: "Brown's Island",
    price: 'Free',
    featured: true,
    sponsored: true,
    hiddenGem: false,
    trendingScore: 92,
    when: ['today', 'weekend', 'week'],
    source: 'Downtown venue',
    sourceType: 'venue',
    sourcePlatform: 'eventbrite',
    sourceUrl: 'https://www.eventbrite.com/',
    ticketUrl: 'https://www.eventbrite.com/',
    externalId: 'sample-eventbrite-001',
    description: 'Riverfront concert with food trucks and downtown views.',
    lat: 37.533,
    lng: -77.441,
  },
  {
    id: 'rva-002',
    title: 'Carytown Dessert Crawl',
    neighborhood: 'Carytown',
    vibe: ['Food & Drink'],
    day: 'Saturday',
    time: '2:00 PM',
    venue: 'Carytown Mile',
    price: '$15+',
    featured: true,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 88,
    when: ['weekend', 'week'],
    source: 'Local business',
    sourceType: 'business',
    sourcePlatform: 'manual',
    description: 'Self-guided dessert stops and small-shop promos.',
    lat: 37.553,
    lng: -77.484,
  },
  {
    id: 'rva-003',
    title: 'Church Hill Makers Market',
    neighborhood: 'Church Hill',
    vibe: ['Markets', 'Family', 'Free'],
    day: 'Sunday',
    time: '11:00 AM',
    venue: 'Jefferson Park',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 76,
    when: ['weekend', 'week'],
    source: 'Community group',
    sourceType: 'community',
    sourcePlatform: 'manual',
    description: 'Handmade goods, local coffee, and neighborhood vendors.',
    lat: 37.531,
    lng: -77.421,
  },
  {
    id: 'rva-004',
    title: "Scott's Addition Rooftop Mixer",
    neighborhood: "Scott's Addition",
    vibe: ['Networking', 'Nightlife'],
    day: 'Thursday',
    time: '6:30 PM',
    venue: 'Rooftop Lounge',
    price: '$25',
    featured: true,
    sponsored: true,
    hiddenGem: false,
    trendingScore: 85,
    when: ['today', 'week', 'weekend'],
    source: 'Partner venue',
    sourceType: 'venue',
    sourcePlatform: 'posh',
    sourceUrl: 'https://posh.vip/e/sunset-soul-va-exclusive-sunday-funday-tour',
    ticketUrl: 'https://posh.vip/e/sunset-soul-va-exclusive-sunday-funday-tour',
    externalId: 'sunset-soul-va-exclusive-sunday-funday-tour',
    description: 'Post-work networking with founders and creatives.',
    lat: 37.568,
    lng: -77.469,
  },
  {
    id: 'rva-005',
    title: 'Fan District Porch Sessions',
    neighborhood: 'The Fan',
    vibe: ['Live Music', 'Free'],
    day: 'Saturday',
    time: '5:00 PM',
    venue: 'Hanover Ave',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 71,
    when: ['weekend', 'week'],
    source: 'Community',
    sourceType: 'community',
    sourcePlatform: 'manual',
    description: 'Acoustic sets in a walkable Fan pocket.',
    lat: 37.555,
    lng: -77.463,
  },
  {
    id: 'rva-006',
    title: 'Manchester Morning Run Club',
    neighborhood: 'Manchester',
    vibe: ['Fitness', 'Free'],
    day: 'Wednesday',
    time: '6:30 AM',
    venue: 'Floodwall Parking Lot',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: false,
    trendingScore: 62,
    when: ['today', 'week'],
    source: 'Community',
    sourceType: 'community',
    sourcePlatform: 'manual',
    description: 'Social run with coffee after the route.',
    lat: 37.522,
    lng: -77.449,
  },
  {
    id: 'rva-007',
    title: 'After-Work Trivia at Wonderland',
    neighborhood: 'Church Hill',
    vibe: ['Food & Drink', 'Nightlife'],
    day: 'Tuesday',
    time: '7:00 PM',
    venue: 'Wonderland',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 68,
    when: ['today', 'week'],
    source: 'Bar & venue',
    sourceType: 'venue',
    sourcePlatform: 'manual',
    description: 'Low-key trivia night locals actually show up for.',
    lat: 37.528,
    lng: -77.418,
  },
  {
    id: 'rva-008',
    title: 'Downtown Food Truck Row',
    neighborhood: 'Downtown',
    vibe: ['Food & Drink', 'Free'],
    day: 'Today',
    time: '11:30 AM',
    venue: '7th Street Plaza',
    price: 'Free entry',
    featured: false,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 80,
    when: ['today', 'week', 'weekend'],
    source: 'Pop-up vendors',
    sourceType: 'popup',
    sourcePlatform: 'manual',
    description: 'Rotating trucks and quick lunch options.',
    lat: 37.538,
    lng: -77.434,
  },
  {
    id: 'rva-009',
    title: 'Carytown Vinyl Night',
    neighborhood: 'Carytown',
    vibe: ['Live Music', 'Nightlife'],
    day: 'Friday',
    time: '8:00 PM',
    venue: 'Deep Groove Records',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 74,
    when: ['today', 'weekend', 'week'],
    source: 'Local business',
    sourceType: 'business',
    sourcePlatform: 'manual',
    description: 'In-store listening party and local DJ sets.',
    lat: 37.554,
    lng: -77.486,
  },
  {
    id: 'rva-010',
    title: 'Family Story Hour at Library',
    neighborhood: 'The Fan',
    vibe: ['Family', 'Free'],
    day: 'Saturday',
    time: '10:00 AM',
    venue: 'Richmond Public Library',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: false,
    trendingScore: 55,
    when: ['weekend', 'week'],
    source: 'Community',
    sourceType: 'community',
    sourcePlatform: 'manual',
    description: 'Morning story time for kids under 8.',
    lat: 37.552,
    lng: -77.461,
  },
  {
    id: 'rva-011',
    title: "SA Brewery Tour & Tasting",
    neighborhood: "Scott's Addition",
    vibe: ['Food & Drink', 'Nightlife'],
    day: 'Saturday',
    time: '1:00 PM',
    venue: 'Brewery Row',
    price: '$20',
    featured: true,
    sponsored: true,
    hiddenGem: false,
    trendingScore: 90,
    when: ['weekend', 'week'],
    source: 'Venue partner',
    sourceType: 'venue',
    sourcePlatform: 'manual',
    description: 'Guided tasting across three Scott’s Addition breweries.',
    lat: 37.566,
    lng: -77.472,
  },
  {
    id: 'rva-012',
    title: 'Manchester Night Market',
    neighborhood: 'Manchester',
    vibe: ['Markets', 'Food & Drink', 'Free'],
    day: 'Friday',
    time: '5:00 PM',
    venue: 'Hull Street',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 83,
    when: ['today', 'weekend', 'week'],
    source: 'Market organizer',
    sourceType: 'market',
    sourcePlatform: 'manual',
    description: 'Small vendors, live DJ, and walkable street energy.',
    lat: 37.52,
    lng: -77.446,
  },
  {
    id: 'rva-013',
    title: 'Startup Coffee Chat',
    neighborhood: 'Downtown',
    vibe: ['Networking', 'Free'],
    day: 'Today',
    time: '8:30 AM',
    venue: 'CoLab Cafe',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: true,
    trendingScore: 64,
    when: ['today', 'week'],
    source: 'Organizer submission',
    sourceType: 'organizer',
    sourcePlatform: 'manual',
    description: 'Casual founder meetup before the workday.',
    lat: 37.536,
    lng: -77.438,
  },
  {
    id: 'rva-014',
    title: 'Sunrise Yoga at Belle Isle',
    neighborhood: 'Manchester',
    vibe: ['Fitness', 'Free'],
    day: 'Sunday',
    time: '8:00 AM',
    venue: 'Belle Isle',
    price: 'Free',
    featured: false,
    sponsored: false,
    hiddenGem: false,
    trendingScore: 70,
    when: ['weekend', 'week'],
    source: 'Community',
    sourceType: 'community',
    sourcePlatform: 'manual',
    description: 'Outdoor yoga with river views. Bring a mat.',
    lat: 37.525,
    lng: -77.455,
  },
  {
    id: 'rva-015',
    title: 'Church Hill Jazz Brunch',
    neighborhood: 'Church Hill',
    vibe: ['Live Music', 'Food & Drink'],
    day: 'Sunday',
    time: '11:00 AM',
    venue: 'The Hill Cafe',
    price: '$18+',
    featured: true,
    sponsored: false,
    hiddenGem: false,
    trendingScore: 87,
    when: ['weekend', 'week'],
    source: 'Restaurant partner',
    sourceType: 'business',
    sourcePlatform: 'manual',
    description: 'Live jazz trio and neighborhood brunch crowd.',
    lat: 37.53,
    lng: -77.419,
  },
];

export const lists: CuratedList[] = [
  {
    id: 'date-night',
    title: 'Date night in RVA',
    by: 'RVA Now',
    description: 'Walkable dinners, drinks, and low-pressure plans.',
    items: ['Carytown Dessert Crawl', "Scott's Addition Rooftop Mixer", 'Church Hill Jazz Brunch'],
    eventSlugs: ['rva-002', 'rva-004', 'rva-015'],
  },
  {
    id: 'free-weekend',
    title: 'Free things this weekend',
    by: 'RVA Now',
    description: 'No cover, no excuse.',
    items: ["Sunset on Brown's Island", 'Church Hill Makers Market', 'Fan District Porch Sessions', 'Manchester Night Market'],
    eventSlugs: ['rva-001', 'rva-003', 'rva-005', 'rva-012'],
  },
  {
    id: 'hidden-gems',
    title: 'Hidden local gems',
    by: 'Neighborhood curators',
    description: 'Smaller events big platforms miss.',
    items: ['After-Work Trivia at Wonderland', 'Carytown Vinyl Night', 'Downtown Food Truck Row', 'Startup Coffee Chat'],
    eventSlugs: ['rva-007', 'rva-009', 'rva-008', 'rva-013'],
  },
  {
    id: 'after-work',
    title: 'Things to do after work',
    by: 'RVA Now',
    description: 'Weeknight-friendly and close to downtown.',
    items: ["Scott's Addition Rooftop Mixer", 'After-Work Trivia at Wonderland', 'Startup Coffee Chat'],
    eventSlugs: ['rva-004', 'rva-007', 'rva-013'],
  },
  {
    id: 'dog-friendly',
    title: 'Dog-friendly spots & events',
    by: 'Community picks',
    description: 'Bring the pup — patios and parks welcome.',
    items: ['Manchester Morning Run Club', 'Downtown Food Truck Row', 'Fan District Porch Sessions'],
    eventSlugs: ['rva-006', 'rva-008', 'rva-005'],
  },
  {
    id: 'black-owned',
    title: 'Black-owned events & businesses',
    by: 'RVA Now',
    description: 'Support and discover local Black-owned happenings.',
    items: ['Manchester Night Market', 'Church Hill Jazz Brunch', 'Church Hill Makers Market'],
    eventSlugs: ['rva-012', 'rva-015', 'rva-003'],
  },
];
