import type { Place } from '@/types/place';

/** Pull places rated 4.2+ onto the map. */
export const MIN_GOOD_RATING = 4.2;

function place(
  partial: Omit<Place, 'source' | 'postCount' | 'lastActiveAt' | 'recentHandles'> & {
    rating: number;
    reviewCount: number;
  },
): Place {
  return {
    ...partial,
    source: 'reviews',
    postCount: 0,
    lastActiveAt: new Date().toISOString(),
    recentHandles: [],
  };
}

/**
 * Well-reviewed RVA spots (sample pull, 4.2+).
 * Later this can come from Google/Yelp/Apple.
 */
export const reviewedPlaces: Place[] = [
  place({
    id: 'rev-lopossum',
    name: "L'Opossum",
    category: 'eat',
    subcategory: 'French · fine dining',
    neighborhood: 'Oregon Hill',
    description: 'Inventive French plates with consistently excellent reviews.',
    emoji: '🍽️',
    priceLevel: '$$$$',
    lat: 37.5401,
    lng: -77.4532,
    rating: 4.8,
    reviewCount: 842,
    featured: true,
  }),
  place({
    id: 'rev-perlys',
    name: "Perly's",
    category: 'eat',
    subcategory: 'Jewish deli · brunch',
    neighborhood: 'Downtown',
    description: 'Downtown deli favorite with strong local ratings.',
    emoji: '🥯',
    priceLevel: '$$',
    lat: 37.5412,
    lng: -77.4378,
    rating: 4.6,
    reviewCount: 1204,
  }),
  place({
    id: 'rev-subrosa',
    name: 'Sub Rosa Bakery',
    category: 'cafes',
    subcategory: 'Bakery · coffee',
    neighborhood: 'Church Hill',
    description: 'Wood-fired bread and coffee with top-tier reviews.',
    emoji: '☕',
    priceLevel: '$',
    lat: 37.5328,
    lng: -77.4165,
    rating: 4.7,
    reviewCount: 956,
    featured: true,
  }),
  place({
    id: 'rev-jasper',
    name: 'The Jasper',
    category: 'bars',
    subcategory: 'Cocktails · late night',
    neighborhood: "Scott's Addition",
    description: 'Craft cocktails and a highly rated Scott’s Addition bar.',
    emoji: '🍸',
    priceLevel: '$$',
    lat: 37.5694,
    lng: -77.4688,
    rating: 4.7,
    reviewCount: 688,
  }),
  place({
    id: 'rev-chopsuey',
    name: 'Chop Suey Books',
    category: 'shops',
    subcategory: 'Bookstore',
    neighborhood: 'Carytown',
    description: 'Independent bookstore with excellent community reviews.',
    emoji: '📚',
    priceLevel: '$$',
    lat: 37.5528,
    lng: -77.4792,
    rating: 4.8,
    reviewCount: 512,
  }),
  place({
    id: 'rev-legend',
    name: 'Legend Brewing Co.',
    category: 'bars',
    subcategory: 'Brewery · river views',
    neighborhood: 'Manchester',
    description: 'Manchester patio staple with strong ratings.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5234,
    lng: -77.4412,
    rating: 4.5,
    reviewCount: 2103,
  }),
  place({
    id: 'rev-croakers',
    name: "Croaker's Spot",
    category: 'eat',
    subcategory: 'Seafood · soul food',
    neighborhood: 'Jackson Ward',
    description: 'Seafood and soul food institution with loyal reviews.',
    emoji: '🐟',
    priceLevel: '$$',
    lat: 37.5489,
    lng: -77.4398,
    rating: 4.5,
    reviewCount: 1788,
  }),
  place({
    id: 'rev-triple',
    name: 'Triple Crossing Brewing',
    category: 'bars',
    subcategory: 'Brewery · patio',
    neighborhood: 'Fulton',
    description: 'Highly rated local brewery with a big patio crowd.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5256,
    lng: -77.4122,
    rating: 4.6,
    reviewCount: 1432,
  }),
  place({
    id: 'rev-mama-js',
    name: "Mama J's",
    category: 'eat',
    subcategory: 'Southern · comfort food',
    neighborhood: 'Jackson Ward',
    description: 'Southern comfort food with standout reviews.',
    emoji: '🍗',
    priceLevel: '$$',
    lat: 37.5478,
    lng: -77.4385,
    rating: 4.6,
    reviewCount: 2450,
    featured: true,
  }),
  place({
    id: 'rev-sugar-shack',
    name: 'Sugar Shack Donuts',
    category: 'cafes',
    subcategory: 'Donuts · coffee',
    neighborhood: "Scott's Addition",
    description: 'Local donut shop with consistently great ratings.',
    emoji: '🍩',
    priceLevel: '$',
    lat: 37.5702,
    lng: -77.4695,
    rating: 4.5,
    reviewCount: 1890,
  }),
  place({
    id: 'rev-vmfa',
    name: 'VMFA',
    category: 'shops',
    subcategory: 'Museum · culture',
    neighborhood: 'Museum District',
    description: 'Top-rated museum and grounds in the Museum District.',
    emoji: '🖼️',
    priceLevel: '$',
    lat: 37.5562,
    lng: -77.4748,
    rating: 4.8,
    reviewCount: 3201,
  }),
  place({
    id: 'rev-broadberry',
    name: 'The Broadberry',
    category: 'nightlife',
    subcategory: 'Live music · venue',
    neighborhood: "Scott's Addition",
    description: 'Live music venue with strong show-night reviews.',
    emoji: '🪩',
    priceLevel: '$$',
    lat: 37.5688,
    lng: -77.4701,
    rating: 4.5,
    reviewCount: 974,
  }),
  place({
    id: 'rev-kuba-kuba',
    name: 'Kuba Kuba',
    category: 'eat',
    subcategory: 'Cuban · casual',
    neighborhood: 'The Fan',
    description: 'Fan favorite for Cuban plates and brunch.',
    emoji: '🌮',
    priceLevel: '$$',
    lat: 37.5518,
    lng: -77.4602,
    rating: 4.4,
    reviewCount: 1670,
  }),
  place({
    id: 'rev-joe',
    name: "Joe's Inn",
    category: 'eat',
    subcategory: 'Italian · comfort',
    neighborhood: 'The Fan',
    description: 'Classic Fan Italian with loyal regulars.',
    emoji: '🍝',
    priceLevel: '$$',
    lat: 37.5526,
    lng: -77.4618,
    rating: 4.3,
    reviewCount: 1544,
  }),
  place({
    id: 'rev-helenas',
    name: "Helena's",
    category: 'eat',
    subcategory: 'Greek · Mediterranean',
    neighborhood: 'Carytown',
    description: 'Carytown Greek spot with solid reviews.',
    emoji: '🥙',
    priceLevel: '$$',
    lat: 37.5531,
    lng: -77.4808,
    rating: 4.4,
    reviewCount: 890,
  }),
  place({
    id: 'rev-can-can',
    name: 'Can Can Brasserie',
    category: 'eat',
    subcategory: 'French · brasserie',
    neighborhood: 'Carytown',
    description: 'Carytown brasserie with strong brunch and dinner ratings.',
    emoji: '🥐',
    priceLevel: '$$$',
    lat: 37.5524,
    lng: -77.4786,
    rating: 4.3,
    reviewCount: 1320,
  }),
  place({
    id: 'rev-proper-pie',
    name: 'Proper Pie Co.',
    category: 'eat',
    subcategory: 'Savory pies · casual',
    neighborhood: 'Church Hill',
    description: 'Savory pies and a Church Hill favorite.',
    emoji: '🥧',
    priceLevel: '$$',
    lat: 37.5319,
    lng: -77.4178,
    rating: 4.6,
    reviewCount: 760,
  }),
  place({
    id: 'rev-zzq',
    name: 'ZZQ Texas Craft Barbeque',
    category: 'eat',
    subcategory: 'BBQ · smoked meats',
    neighborhood: "Scott's Addition",
    description: 'Texas-style BBQ with excellent ratings.',
    emoji: '🍖',
    priceLevel: '$$',
    lat: 37.5682,
    lng: -77.4671,
    rating: 4.6,
    reviewCount: 2011,
  }),
  place({
    id: 'rev-secret-sandwich',
    name: 'Secret Sandwich Society',
    category: 'eat',
    subcategory: 'Sandwiches · casual',
    neighborhood: 'Carytown',
    description: 'Creative sandwiches with a strong following.',
    emoji: '🥪',
    priceLevel: '$$',
    lat: 37.5536,
    lng: -77.4819,
    rating: 4.4,
    reviewCount: 1188,
  }),
  place({
    id: 'rev-early-bird',
    name: 'Early Bird Biscuit',
    category: 'cafes',
    subcategory: 'Biscuits · breakfast',
    neighborhood: 'Church Hill',
    description: 'Breakfast biscuits with top local reviews.',
    emoji: '🍳',
    priceLevel: '$',
    lat: 37.5334,
    lng: -77.4189,
    rating: 4.5,
    reviewCount: 940,
  }),
  place({
    id: 'rev-blanchards',
    name: "Blanchard's Coffee",
    category: 'cafes',
    subcategory: 'Coffee · study spot',
    neighborhood: 'The Fan',
    description: 'Local roaster with a steady Fan crowd.',
    emoji: '☕',
    priceLevel: '$',
    lat: 37.5521,
    lng: -77.4624,
    rating: 4.5,
    reviewCount: 812,
  }),
  place({
    id: 'rev-black-hand',
    name: 'Black Hand Coffee',
    category: 'cafes',
    subcategory: 'Coffee · espresso',
    neighborhood: 'Manchester',
    description: 'Manchester coffee bar with strong ratings.',
    emoji: '☕',
    priceLevel: '$',
    lat: 37.5248,
    lng: -77.4428,
    rating: 4.6,
    reviewCount: 540,
  }),
  place({
    id: 'rev-lift',
    name: 'Lift Coffee Shop & Cafe',
    category: 'cafes',
    subcategory: 'Coffee · cafe',
    neighborhood: 'Shockoe Bottom',
    description: 'Shockoe Bottom cafe with loyal regulars.',
    emoji: '☕',
    priceLevel: '$',
    lat: 37.5339,
    lng: -77.4295,
    rating: 4.3,
    reviewCount: 1102,
  }),
  place({
    id: 'rev-garden-grove',
    name: 'Garden Grove Brewing',
    category: 'bars',
    subcategory: 'Brewery · patio',
    neighborhood: 'Carytown',
    description: 'Carytown brewery with solid patio reviews.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5541,
    lng: -77.4826,
    rating: 4.4,
    reviewCount: 980,
  }),
  place({
    id: 'rev-veils',
    name: 'The Veil Brewing Co.',
    category: 'bars',
    subcategory: 'Brewery · hazy IPAs',
    neighborhood: "Scott's Addition",
    description: 'Scott’s Addition brewery with a big following.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5711,
    lng: -77.4662,
    rating: 4.5,
    reviewCount: 1560,
  }),
  place({
    id: 'rev-strangeways',
    name: 'Strangeways Brewing',
    category: 'bars',
    subcategory: 'Brewery · beer garden',
    neighborhood: 'Scott\'s Addition',
    description: 'Beer garden energy and strong local ratings.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5675,
    lng: -77.4648,
    rating: 4.4,
    reviewCount: 1220,
  }),
  place({
    id: 'rev-saison',
    name: 'Saison',
    category: 'bars',
    subcategory: 'Cocktails · wine',
    neighborhood: 'Scott\'s Addition',
    description: 'Cocktail bar with excellent reviews.',
    emoji: '🍸',
    priceLevel: '$$$',
    lat: 37.5698,
    lng: -77.4708,
    rating: 4.6,
    reviewCount: 640,
  }),
  place({
    id: 'rev-brill',
    name: 'Brill',
    category: 'bars',
    subcategory: 'Cocktails · late night',
    neighborhood: 'Carytown',
    description: 'Carytown cocktail bar with strong ratings.',
    emoji: '🍸',
    priceLevel: '$$',
    lat: 37.5529,
    lng: -77.4799,
    rating: 4.5,
    reviewCount: 710,
  }),
  place({
    id: 'rev-bygones',
    name: 'Bygones Vintage',
    category: 'shops',
    subcategory: 'Vintage · clothing',
    neighborhood: 'Carytown',
    description: 'Carytown vintage for a weekend wander.',
    emoji: '👗',
    priceLevel: '$$',
    lat: 37.5534,
    lng: -77.4801,
    rating: 4.6,
    reviewCount: 430,
  }),
  place({
    id: 'rev-world-of-mirth',
    name: 'World of Mirth',
    category: 'shops',
    subcategory: 'Toys · gifts',
    neighborhood: 'Carytown',
    description: 'Toy and gift shop with great family reviews.',
    emoji: '🎁',
    priceLevel: '$$',
    lat: 37.5538,
    lng: -77.4812,
    rating: 4.7,
    reviewCount: 880,
  }),
  place({
    id: 'rev-fountain',
    name: 'Fountain Bookstore',
    category: 'shops',
    subcategory: 'Bookstore',
    neighborhood: 'Shockoe Slip',
    description: 'Independent bookstore in Shockoe Slip.',
    emoji: '📚',
    priceLevel: '$$',
    lat: 37.5331,
    lng: -77.4338,
    rating: 4.7,
    reviewCount: 390,
  }),
  place({
    id: 'rev-quirk',
    name: 'Quirk Hotel',
    category: 'nightlife',
    subcategory: 'Rooftop · hotel bar',
    neighborhood: 'Arts District',
    description: 'Rooftop views and a popular hotel bar.',
    emoji: '🌃',
    priceLevel: '$$$',
    lat: 37.5456,
    lng: -77.4419,
    rating: 4.4,
    reviewCount: 2100,
  }),
  place({
    id: 'rev-national',
    name: 'The National',
    category: 'nightlife',
    subcategory: 'Live music · venue',
    neighborhood: 'Downtown',
    description: 'Downtown live music venue with solid show reviews.',
    emoji: '🎤',
    priceLevel: '$$',
    lat: 37.5419,
    lng: -77.4356,
    rating: 4.5,
    reviewCount: 1450,
  }),
  place({
    id: 'rev-broadberry-2',
    name: 'The Camel',
    category: 'nightlife',
    subcategory: 'Live music · bar',
    neighborhood: 'Arts District',
    description: 'Intimate live music room with loyal fans.',
    emoji: '🎸',
    priceLevel: '$$',
    lat: 37.5468,
    lng: -77.4432,
    rating: 4.6,
    reviewCount: 820,
  }),
  place({
    id: 'rev-carytown-burgers',
    name: 'Carytown Burgers & Fries',
    category: 'eat',
    subcategory: 'Burgers · casual',
    neighborhood: 'Carytown',
    description: 'Casual burgers with consistently good ratings.',
    emoji: '🍔',
    priceLevel: '$$',
    lat: 37.5532,
    lng: -77.4804,
    rating: 4.3,
    reviewCount: 1605,
  }),
  place({
    id: 'rev-sticky-rice',
    name: 'Sticky Rice',
    category: 'eat',
    subcategory: 'Sushi · Asian',
    neighborhood: 'The Fan',
    description: 'Fan sushi spot with strong reviews.',
    emoji: '🍣',
    priceLevel: '$$',
    lat: 37.5512,
    lng: -77.4591,
    rating: 4.3,
    reviewCount: 990,
  }),
  place({
    id: 'rev-edo',
    name: "Edo's Squid",
    category: 'eat',
    subcategory: 'Italian · seafood',
    neighborhood: 'The Fan',
    description: 'Italian seafood classic in the Fan.',
    emoji: '🦑',
    priceLevel: '$$$',
    lat: 37.5504,
    lng: -77.4582,
    rating: 4.4,
    reviewCount: 1402,
  }),
  place({
    id: 'rev-millies',
    name: "Millie's Diner",
    category: 'eat',
    subcategory: 'Brunch · American',
    neighborhood: 'Shockoe Bottom',
    description: 'Brunch institution with longtime fans.',
    emoji: '🥞',
    priceLevel: '$$',
    lat: 37.5326,
    lng: -77.4288,
    rating: 4.4,
    reviewCount: 1880,
  }),
  place({
    id: 'rev-dutch-white',
    name: '&Pizza',
    category: 'eat',
    subcategory: 'Pizza · casual',
    neighborhood: 'Carytown',
    description: 'Fast casual pizza with solid ratings.',
    emoji: '🍕',
    priceLevel: '$$',
    lat: 37.5544,
    lng: -77.4831,
    rating: 4.2,
    reviewCount: 760,
  }),
  place({
    id: 'rev-origin',
    name: 'Origin Beer Garden',
    category: 'bars',
    subcategory: 'Beer garden · patio',
    neighborhood: 'Scott\'s Addition',
    description: 'Beer garden patio with good local reviews.',
    emoji: '🍻',
    priceLevel: '$$',
    lat: 37.5708,
    lng: -77.4681,
    rating: 4.3,
    reviewCount: 1120,
  }),
  place({
    id: 'rev-final-gravity',
    name: 'Final Gravity Brewing',
    category: 'bars',
    subcategory: 'Brewery · neighborhood',
    neighborhood: 'Lakeside',
    description: 'Neighborhood brewery with friendly ratings.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.6088,
    lng: -77.4621,
    rating: 4.5,
    reviewCount: 680,
  }),
  place({
    id: 'rev-hardywood',
    name: 'Hardywood Park Craft Brewery',
    category: 'bars',
    subcategory: 'Brewery · campus',
    neighborhood: 'Scott\'s Addition',
    description: 'Large brewery campus with strong reviews.',
    emoji: '🍺',
    priceLevel: '$$',
    lat: 37.5669,
    lng: -77.4635,
    rating: 4.5,
    reviewCount: 2400,
  }),
  place({
    id: 'rev-capital-ale',
    name: 'Capital Ale House',
    category: 'bars',
    subcategory: 'Beer · pub food',
    neighborhood: 'Downtown',
    description: 'Downtown beer hall with solid ratings.',
    emoji: '🍻',
    priceLevel: '$$',
    lat: 37.5408,
    lng: -77.4369,
    rating: 4.2,
    reviewCount: 1750,
  }),
  place({
    id: 'rev-riverside',
    name: 'Riverside Outfitters',
    category: 'fitness',
    subcategory: 'Outdoor · rentals',
    neighborhood: 'James River',
    description: 'River access and outdoor gear with great reviews.',
    emoji: '🛶',
    priceLevel: '$$',
    lat: 37.5298,
    lng: -77.4502,
    rating: 4.6,
    reviewCount: 920,
  }),
  place({
    id: 'rev-maymont',
    name: 'Maymont',
    category: 'shops',
    subcategory: 'Park · gardens',
    neighborhood: 'Byrd Park',
    description: 'Gardens and grounds with excellent visitor ratings.',
    emoji: '🌳',
    priceLevel: '$',
    lat: 37.5348,
    lng: -77.4782,
    rating: 4.7,
    reviewCount: 4100,
  }),
  place({
    id: 'rev-lewis-ginter',
    name: 'Lewis Ginter Botanical Garden',
    category: 'shops',
    subcategory: 'Garden · attraction',
    neighborhood: 'Lakeside',
    description: 'Botanical gardens with top visitor reviews.',
    emoji: '🌸',
    priceLevel: '$$',
    lat: 37.6204,
    lng: -77.4708,
    rating: 4.8,
    reviewCount: 5200,
  }),
  place({
    id: 'rev-carytown-market',
    name: 'Carytown Farmers Market',
    category: 'markets',
    subcategory: 'Weekend market',
    neighborhood: 'Carytown',
    description: 'Local produce and makers on market days.',
    emoji: '🥬',
    priceLevel: '$',
    lat: 37.5539,
    lng: -77.4815,
    rating: 4.6,
    reviewCount: 640,
  }),
  place({
    id: 'rev-17th-market',
    name: '17th Street Farmers Market',
    category: 'markets',
    subcategory: 'Market · outdoor',
    neighborhood: 'Shockoe Bottom',
    description: 'Historic market with strong weekend reviews.',
    emoji: '🧺',
    priceLevel: '$',
    lat: 37.5322,
    lng: -77.4281,
    rating: 4.4,
    reviewCount: 880,
  }),
  place({
    id: 'rev-southbound',
    name: 'Southbound',
    category: 'eat',
    subcategory: 'Southern · brunch',
    neighborhood: 'Manchester',
    description: 'Manchester brunch and dinner with good ratings.',
    emoji: '🍳',
    priceLevel: '$$',
    lat: 37.5259,
    lng: -77.4401,
    rating: 4.3,
    reviewCount: 970,
  }),
  place({
    id: 'rev-lunch-supper',
    name: 'Lunch / Supper',
    category: 'eat',
    subcategory: 'Southern · seasonal',
    neighborhood: 'Scott\'s Addition',
    description: 'Seasonal Southern plates with strong reviews.',
    emoji: '🥗',
    priceLevel: '$$$',
    lat: 37.5691,
    lng: -77.4692,
    rating: 4.4,
    reviewCount: 860,
  }),
  place({
    id: 'rev-ale-wife',
    name: 'Alewife',
    category: 'eat',
    subcategory: 'Seafood · oysters',
    neighborhood: 'Scott\'s Addition',
    description: 'Seafood and oysters with excellent ratings.',
    emoji: '🦪',
    priceLevel: '$$$',
    lat: 37.5685,
    lng: -77.4684,
    rating: 4.5,
    reviewCount: 1020,
  }),
  place({
    id: 'rev-tarrant',
    name: "Tarrant's Cafe",
    category: 'eat',
    subcategory: 'American · cafe',
    neighborhood: 'Shockoe Slip',
    description: 'Shockoe Slip cafe with longtime fans.',
    emoji: '☕',
    priceLevel: '$$',
    lat: 37.5336,
    lng: -77.4344,
    rating: 4.2,
    reviewCount: 1340,
  }),
  place({
    id: 'rev-penny-lane',
    name: 'Penny Lane Pub',
    category: 'bars',
    subcategory: 'Pub · British',
    neighborhood: 'Shockoe Slip',
    description: 'British pub vibes with solid reviews.',
    emoji: '🍻',
    priceLevel: '$$',
    lat: 37.5334,
    lng: -77.4331,
    rating: 4.3,
    reviewCount: 910,
  }),
];

export function pullWellReviewedPlaces(minRating = MIN_GOOD_RATING) {
  return reviewedPlaces.filter((place) => (place.rating ?? 0) >= minRating);
}
